source 'http://rubygems.org'
ruby '2.0.0'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'mongo_mapper', '0.13.0.beta2'
gem 'sinatra-authentication', :git => 'https://github.com/maxjustus/sinatra-authentication.git', :branch => 'master'
gem 'bson_ext'
gem 'encrypted_cookie'
gem 'rack'
gem 'haml'
gem 'rack_csrf'
gem 'thin'
gem 'pony'
gem 'rack-flash3'
gem 'rack-oauth2-server'
gem 'rack-test'
gem 'minitest'
gem 'iconv'
gem 'dotenv'
